webserver:
   container_name: woocommerce
   build: ./
   links:
    - dbserver:mysql
   ports:
    - 8080:80

dbserver:
   container_name: mariadb
   image: mariadb
   environment:
    MYSQL_ROOT_PASSWORD: example
   ports:
    - 3307:3306
